services:
  mariadb:
    container_name: mariadb			# Le nom du container, oui vraiment.
    build: 
      context: ./requirements/mariadb 	# ou se trouve son Dockerfile
    env_file: 
      - .env                  # le fichier d'environnement pour transmettre les variables
    volumes:                        # Voir plus bas
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    networks: 
      - inception            			# à quel network il appartient
    expose:                         # le port à exposer
      - "3306"

  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443" 		# on indique le port qui sera exposé a la machine locale
    depends_on:        			 # Nouvelle ligne, indiquant de ne pas démarrer NGINX tant que WordPress n'a pas démarré.
      - wordpress
    restart: always 		# Ici nous changeons, le container redémarrera uniquement en cas de crash.
    env_file: 
      - .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    env_file: 
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    build: 
      context: ./requirements/wordpress
    restart: on-failure
    expose: 
      - "9000"
    networks:
      - inception
    
    
volumes:
  wordpress:
    driver: local # ici nous stockons le volume en local
    driver_opts:
      type: none							# aucun type spécifique
      o: bind
      device: /home/ambre/data/wordpress 		#Ou stocker le dossier sur votre ordinateur en local
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind	      # Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
      device: /home/ambre/data/mysql			#Ou stocker le dossier sur votre ordinateur en local

networks:
  inception:
    driver: bridge

#######################################################################################

#version: '3.8'

#services:

#  nginx:
#    container_name: nginx
#    build: ./requirements/nginx
#    volumes:
#      - wordpress:/var/www/wordpress
#    ports:
#      - "443:443"
#    depends_on:
#      - wordpress
#    restart: always
#    env_file:
#      - .env
#    networks:
#      - inception
#
#  mariadb:
#    container_name: mariadb
#    build:
#      context: ./requirements/mariadb
#    env_file:
#      - .env
#    volumes:
#      - mariadb:/var/lib/mysql
#    restart: unless-stopped
#    networks:
#      - inception
#    expose:
#      - "3306"
#
#  wordpress:
#    container_name: wordpress
#    env_file:
#      - .env
#    volumes:
#      - wordpress:/var/www/wordpress
#    depends_on:
#      - mariadb
#    build:
#      context: ./requirements/wordpress
#    restart: on-failure
#    expose:
#      - "9000"
#    networks:
#      - inception
#
#volumes:
#  mariadb:
#    driver: local
#    driver_opts:
#        type: volumes
#        o: bind
#        device: /home/aclement/data/mysql
#
#  wordpress:
#    driver: local
#    driver_opts:
#        type: volumes
#        o: bind
#        device: /home/aclement/data/wordpress
#
#networks:
#  inception:
#      driver: bridge

